# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Update Partition Matrix
NULL

Basis_Expansion <- function(y, X, initial_alpha, initial_a, initial_delta, initial_z, initial_theta, initial_prob_mat, excluded_vox, poly_degree, poly_a, poly_b, radius_candidats, partition, oc_theta = TRUE, oc_alpha = TRUE, oc_delta = TRUE, oc_z = TRUE, oc_sigma = TRUE, oc_a = TRUE, initial_sigma_sq = 1, threshold = 0.5, prior_max = 1, prior_min = 0, mcmc_sample = 500L, burnin = 5000L, thinning = 10L, radius_update_thinning = 50L, max_iter = 1000L, verbose = 5000L, save_profile = 1L) {
    .Call(`_sasbcar_Basis_Expansion`, y, X, initial_alpha, initial_a, initial_delta, initial_z, initial_theta, initial_prob_mat, excluded_vox, poly_degree, poly_a, poly_b, radius_candidats, partition, oc_theta, oc_alpha, oc_delta, oc_z, oc_sigma, oc_a, initial_sigma_sq, threshold, prior_max, prior_min, mcmc_sample, burnin, thinning, radius_update_thinning, max_iter, verbose, save_profile)
}

update_pj_mat <- function(delta_mat, partition, radius_partition) {
    .Call(`_sasbcar_update_pj_mat`, delta_mat, partition, radius_partition)
}

